### PR TITLE
make ChainRulesCore dependency into an extension

### PR DESCRIPTION
**Pull request by KristofferC**
Shouldn't be merged until the Registrator deployment of https://github.com/JuliaRegistries/Registrator.jl/pull/397 is done.

### CODE REVIEW

**Comment by oschulz** [comment]
@KristofferC I hadn't been aware of Pkg extensions until just now (but I'm very much in favor of the concept!) - which Julia version will this require? And does it eliminate the drawbacks of Requires.jl (no precompilation and often big hit on load time of stacks of packages)?

**Comment by KristofferC** [comment]
Should be backwards compatible to Julia 1.0.

>  Do extensions eliminate the drawbacks of Requires.jl (no precompilation and often big hit on load time of stacks of packages)?

Yes, that's the idea. These extensions get precompiled like a normal package.

**Comment by oschulz** [comment]
> Yes, that's the idea. These extensions get precompiled like a normal package.

Oh, that is awesome!

**Comment by oschulz** [comment]
> Shouldn't be merged until the Registrator deployment of https://github.com/JuliaRegistries/Registrator.jl/pull/397 is done.

Do you know if that's deployed now?

**Comment by KristofferC** [comment]
Yes, it should be! So we can try this out.

**Comment by oschulz** [comment]
Ok, let's try it! :-)

**Comment by oschulz** [comment]
Seems to work like a charm with Julia v1.9.0-beta3:

```julia
julia> @time_imports import ChangesOfVariables
      0.6 ms  ChangesOfVariables

julia> @time_imports import ChainRulesCore
      0.1 ms  Compat
     58.9 ms  ChainRulesCore
      0.4 ms  ChangesOfVariables → ChainRulesCoreExt
```

@devmotion, if you have no objections I'll tag a ChangesOfVariables release with this?

**Comment by devmotion** [comment]
Sure, I'm really excited about weak dependencies :slightly_smiling_face:

**Comment by oschulz** [comment]
> Sure, I'm really excited about weak dependencies

Me too, I hope this will start a minor (maybe not so minor) revolution across the ecosystem.

**Pull request merged**
